### ISSUE TITLE
[URGENT] List xor

### ISSUE THREAD

**Issue by ClementJ18** [PushBen/PythonChallenges#1]
Good sir,
I write to you in dire need, the future of my company, ClemNet Inc., is in terrible danger. We woke on this day to realize that none of our engineers are able to check that a value appears exclusively in one of two lists. I seek now your services to aid me. 

I need a function that can take an int `n`, two lists `list1` and `list2` and, in a single line (our server space is very limited), return a bool that is True if `n` appears either in `list1` or `list2` and False if it doesn't appear in either or appears in both. I've included an example to help

```
magic(1, [1, 2, 3], [4, 5, 6]) == True 
magic(1, [0, 2, 3], [1, 5, 6]) == True 
magic(1, [1, 2, 3], [1, 5, 6]) == False 
magic(1, [0, 0, 0], [4, 5, 6]) == False
```

Sincerely yours,

ClemNet Inc CEO and Head of HR, Clement

**Comment by PushBen** [comment]
Solution added as XORList.py!
